language: c
jobs:
    include:
        #- os: linux
        - os: osx
          osx_image: xcode11
compiler:
    - clang
    - gcc
before_install:
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install -y cmake zlib1g-dev git libpng16-dev nasm ; fi
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install nasm zlib libpng ; fi
    - git clone https://github.com/mozilla/mozjpeg.git
    - cd mozjpeg
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then mkdir build && cd build && cmake -G"Unix Makefiles" -DPNG_SUPPORTED=TRUE ../ && make SHARED=0 CC='gcc -static' && make install ; fi
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then mkdir build && cd build && cmake -G"Unix Makefiles" -DPNG_SUPPORTED=TRUE -DZLIB_LIBRARY=/usr/local/Cellar/zlib/1.2.11/lib/libz.a -DPNG_PNG_INCLUDE_DIR=/usr/local/Cellar/libpng/1.6.37/include -DPNG_LIBRARY=/usr/local/Cellar/libpng/1.6.37/lib/libpng.a ../ && make SHARED=0 CC='gcc -static' && sudo make install ; fi
    - sudo ln -s /opt/mozjpeg/lib64 /opt/mozjpeg/lib
    - cd ../..
script:
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then LDFLAGS="--static" make ; fi
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then make  ; fi
    - sudo make install
    - ./jpeg-recompress --version
    - cd test
    - ./test.sh
