language: c
compiler:
    #- clang
    - gcc
before_install:
    - sudo apt-get install -y cmake zlib1g-dev git libpng16-dev nasm build-essential autoconf
    - git clone https://github.com/mozilla/mozjpeg.git
    - cd mozjpeg
    - mkdir build && cd build
    - cmake -G"Unix Makefiles" -DPNG_SUPPORTED=TRUE ../
    - make SHARED=0 CC='gcc -static'
    - make install
    - sudo ln -s /opt/mozjpeg/lib64 /opt/mozjpeg/lib
    - cd ../..
script:
    - pwd && sudo make && sudo make install && cd test && test.sh
